### ISSUE TITLE
您好，在控制器中的action中的this.render不能用

### ISSUE THREAD

**Issue by jobsfan** [thinkkoa/koatty#18]
![1111](https://user-images.githubusercontent.com/3395025/90104078-339c9280-dd76-11ea-9be1-f6b49c069df0.png)

我安装了npm i think_view

![22222](https://user-images.githubusercontent.com/3395025/90104154-53cc5180-dd76-11ea-8285-28cdc107bacd.png)

middleware配置如下
![3333](https://user-images.githubusercontent.com/3395025/90104200-6a72a880-dd76-11ea-8f1f-8041a4241cfa.png)

我在vs code编辑器里面，
![4444](https://user-images.githubusercontent.com/3395025/90104618-2cc24f80-dd77-11ea-8869-2341cf5f9e36.png)

**Comment by richenlin** [comment]
hello, `render`函数作为中间件扩展的函数，不再放入BaseController，请使用：`this.ctx.render`

```
@GetMapping("/")
    index() {
        return this.ctx.render('./html/index.html');
    }
```

**Comment by jobsfan** [comment]
> hello, `render`函数作为中间件扩展的函数，不再放入BaseController，请使用：`this.ctx.render`
> 
> ```
> @GetMapping("/")
>     index() {
>         return this.ctx.render('./html/index.html');
>     }
> ```

谢谢！！
