### ISSUE TITLE
不好意思，又来问个问题，如何设置 "Access-Control-Allow-Origin", "*"，不阻止跨域请求

### ISSUE THREAD

**Issue by jobsfan** [thinkkoa/koatty#19]
![1111](https://user-images.githubusercontent.com/3395025/90120571-774ec680-dd8d-11ea-87a4-20cd622a0d3e.png)

如果能统一设置最好，如果不能的话，如何在 controller
![22222](https://user-images.githubusercontent.com/3395025/90120909-e3c9c580-dd8d-11ea-95ff-38adfeafeb05.png)

请帮忙看一下

**Comment by richenlin** [comment]
这种情况，需要使用中间件来进行配置，推荐使用koa的https://github.com/koajs/cors 中间件
怎么使用参考 https://thinkkoa.github.io/koatty_doc/#/?id=%e4%bd%bf%e7%94%a8koa%e4%b8%ad%e9%97%b4%e4%bb%b6

部分代码如下
```
const cors = require('@koa/cors');

@Middleware()
export class PassportMiddleware implements IMiddleware {

    run(options: any, app: App) {
        return cors();
    }
}
```

**Comment by jobsfan** [comment]
这个ok了，谢谢

不好意思，我再问一个问题
现在返回都是一个json格式 {"status":200,"message":"OK","data":"BJ48HFKsZROqGP6T9IUXQCZV0tgbMeM9ENBZiMzBdG23ViGzPYT062_0t2cmJ838qgHyKBhaCEoeurGNXTm6Fx4"}

我想直接返回一个字符串，咋搞？

**Comment by richenlin** [comment]
框架会自动判断request请求头类型，如果请求头包含"application/json"，默认以json格式返回

你可以在控制器中使用
```
return  this.body("text", "text/plain")

```

或者这样写:

```
this.set("Content-Type", "text/plain")
this.ctx.body = "text"


```

**Comment by jobsfan** [comment]
@richenlin 感谢你的回复，
我在控制器之中使用了return  this.body("text", "text/plain") 这个之后，原本已经解决的CORS问题又出现了！欲哭无泪

**Comment by jobsfan** [comment]
您好，等你有空了，教下我，怎么设置响应的状态码，比如设置成201

**Comment by richenlin** [comment]
你检查下cors中间件的配置，看下对方的文档，可能需要配置method

koatty本身是基于koa框架做的薄封装，并没有更改koa原有的机制，koa支持的写法，koatty都是支持的（语法有一点区别）

输出响应状态码:

```
// koa
ctx.status = 201;


// koatty controller

function test(){
    this.ctx.status = 201;
}
```

**Comment by jobsfan** [comment]
> 你检查下cors中间件的配置，看下对方的文档，可能需要配置method
> 
> koatty本身是基于koa框架做的薄封装，并没有更改koa原有的机制，koa支持的写法，koatty都是支持的（语法有一点区别）
> 
> 输出响应状态码:
> 
> ```
> // koa
> ctx.status = 201;
> 
> 
> // koatty controller
> 
> function test(){
>     this.ctx.status = 201;
> }
> ```

谢谢回复！！

能教一下cors中间件的post设置么？现在就按照你上面教的，
增加了CorsMiddleware.ts文件
![1111](https://user-images.githubusercontent.com/3395025/90209527-394db300-de1e-11ea-942a-98294b02729e.png)

然后在middleware.ts里面加了个配置
![22222](https://user-images.githubusercontent.com/3395025/90209550-47033880-de1e-11ea-9406-ec9d48a7d8ef.png)


你有空的话，就教下我，没空的话，我就再去找下资料。不好意思麻烦了

**Comment by richenlin** [comment]
CorsMiddleware: false  ，表示关闭该中间件

正确的配置为:
CorsMiddleware :{
            //cors中间件配置项
            allowMethods: "GET,HEAD,PUT,POST,DELETE,PATCH", //`Access-Control-Allow-Methods`, default is 'GET,HEAD,PUT,POST,DELETE,PATCH'
            exposeHeaders: "", //`Access-Control-Expose-Headers`
            allowHeaders: "", //`Access-Control-Allow-Headers`
            maxAge: "", // `Access-Control-Max-Age` in seconds
}

**Comment by jobsfan** [comment]
我先试下，等会儿来给反馈

**Comment by jobsfan** [comment]
有没有可能是我的中间件没有起作用，我发现static也没有用
![3333](https://user-images.githubusercontent.com/3395025/90213190-b29dd380-de27-11ea-8a42-fe181e4d5940.png)

**Comment by richenlin** [comment]
这里有一个[demo](https://github.com/thinkkoa/koatty_demo/)，供参考

**Comment by jobsfan** [comment]
> 这里有一个[demo](https://github.com/thinkkoa/koatty_demo/)，供参考

![11111](https://user-images.githubusercontent.com/3395025/90214357-cc8ce580-de2a-11ea-8386-4a2f5eee1610.png)

错误提示里面是这样的
![22222222222](https://user-images.githubusercontent.com/3395025/90214460-2097ca00-de2b-11ea-891e-e66ef00a07b9.png)
我好迷啊

**Comment by jobsfan** [comment]
谢谢您耐心的解答！！
