### ISSUE TITLE
can you pls give any mongo configuration demo?

### ISSUE THREAD

**Issue by yif-fast** [thinkkoa/koatty#2]
I found the mysql and redis config in the db.ts, however there is no mongodb config there.

By the way, this framework is the finished and successfull one or it is just under constructing and can not be used for a real project yet? Pls let me known, thank you!

**Comment by richenlin** [comment]
The framework does not restrict you from using any configuration to link the database. If you use a native driver:

db.ts
```
...
 mongo: {
    url: "mongodb://localhost:27017",
    dbName: "myproject"
}
...

```
and use it by @Value("mongo", "db");

**Comment by richenlin** [comment]
The framework has released several stable versions and is still actively being updated, mainly adding new features. And Koatty is widely used in many production projects of our company.

**Comment by yif-fast** [comment]
@richenlin ok, thank you!
