### ISSUE TITLE
Sample example project or documentation on how to use @Middleware 

### ISSUE THREAD

**Issue by dsp1589** [thinkkoa/koatty#22]
Hello,

Where can I find Sample example project or documentation on how to use @Middleware on controller level and path level. My project involves some end points need to be protected and some are open to public.

Any help much appreciated.

**Comment by richenlin** [comment]
@Middleware currently does not support on the controller level and path level😢
Of course you can use `path` for partial control：
```
// TestMiddleware:
@Middleware()
export class TestMiddleware implements IMiddleware {

    run(options: any, app: any) {
        ...
        if (ctx.path == "/public") {
            return next();
        }
        // protected
        ....
    }
}

```
We are considering whether to add support for this new feature, just like this:
```
@Middleware("/test") ==> used to `/test`
@Middleware("TestController", "CONTROLLER") ==> used to TestController
```

We also welcome you to help us submit PR！

**Comment by dsp1589** [comment]
This is helpful. To protect multiple path we need to introduce a new common path like "/public" and check for its presence. Thank you for the quick response and I appreciate it.
