### ISSUE TITLE
confused about the view location

### ISSUE THREAD

**Issue by yif-fast** [thinkkoa/koatty#3]
Hi There, from the demo project [https://github.com/thinkkoa/koatty_demo/](url) I found you placed the views in static/html.

I can unstand that the folder **static** is the common foler to both **src** and **dist**. However if you place the views in static folder, it means the visiters can visit it directly without route. It is not safe in my point of view. Do you have any plan to improve it?

**Comment by richenlin** [comment]
This project uses [think_view](https://github.com/thinkkoa/think_view) middleware, so you can modify the configuration of the middleware to meet your requirements.Edit src/config/middleware.ts:

```
// project root path is process.env.ROOT_PATH
view_path: process.env.ROOT_PATH + '/static',
```
