### ISSUE TITLE
errors after run "npm install"

### ISSUE THREAD

**Issue by yif-fast** [thinkkoa/koatty#5]
![error111](https://user-images.githubusercontent.com/56343991/77499787-07977800-6e8e-11ea-9cff-4033590f3d01.png)

Dear Author,
Today, I start a new project by the following steps:
1. koatty new projectName
2. cd ./projectName
3. npm install

then the above errors shows, pls help.

Thank you in advance!

**Comment by richenlin** [comment]
The think_validtion package that the framework depends on fails to download properly. You can try to switch the npm image: nrm use taobao

**Comment by yif-fast** [comment]
> The think_validtion package that the framework depends on fails to download properly. You can try to switch the npm mirror:
> 
> ```
> npm i -g nrm
> 
> nrm use taobao
> ```
> 
> or used
> `yarn install`

Hi @thinkkoa, thanks for your reply!!

I tried your suggested cmd:
1. npm i -g nrm
2. nrm use taobao
3. npm install

As well I updated my nodejs version to v12.16.1, it is the latest stable version.

when I run 'npm start' I got something new:

![xxxx1](https://user-images.githubusercontent.com/56343991/77511832-da0df700-6eac-11ea-9da1-aa21c7629136.png)

![2222](https://user-images.githubusercontent.com/56343991/77512031-2d804500-6ead-11ea-8a75-6b7331be31af.png)

Sorry for troubling.

**Comment by richenlin** [comment]
Confirm the koatty version in your project package.json is the latest version

"koatty": "^ 1.19.3"

**Comment by richenlin** [comment]
If you pull the koatty_demo project, please git pull again, the problem has just been fixed

**Comment by richenlin** [comment]
Finally, don't forget that the cli tool must also be upgraded to 1.19.x
npm i -g koatty_cli

**Comment by yif-fast** [comment]
@richenlin 
I run 'npm i -g koatty_cli@latest' and 'npm i -g koatty_cli', both way, my koatty version is koatty_cli@1.18.0

I dont't know how to upgrade this. pls help me.

By the way, if I wanna to use 'https://github.com/Lierrmm/Node-CallOfDuty' in my project.
Is it possible?
I install this module via 'npm install call-of-duty-api --save', however it says can not find this module.
`import { CodAPI } from "call-of-duty-api"`

**Comment by richenlin** [comment]
1、Recommend using yarn to manage dependencies
```shell
curl -o- -L https://yarnpkg.com/install.sh | bash

```
upgrade or install module:

```
yarn add koatty@1.19.2
```
2、This project is not packaged as an npm module. You can download the index.js file locally and rename it "CallOfDuty.js"

Introduced in the program:

`` `
const CallOfDuty = require ("./ CallOfDuty.js");
`` `

**Comment by yif-fast** [comment]
@richenlin  did a great favor to me,  thank you so much for your fast reply!
