### ISSUE TITLE
when I use a module which used to scrapy data via https, error shows

### ISSUE THREAD

**Issue by yif-fast** [thinkkoa/koatty#6]
Hi @richenlin 

Sorry for troubling you!

![1111](https://user-images.githubusercontent.com/56343991/77519104-e2b8fa00-6eb9-11ea-9954-ae56d1fb41af.png)

The following are the console screenshot:
![2222](https://user-images.githubusercontent.com/56343991/77519335-46dbbe00-6eba-11ea-9604-8ccb946494f3.png)

![33333](https://user-images.githubusercontent.com/56343991/77519527-a0dc8380-6eba-11ea-8895-edb0a87ab66b.png)

Do you have any idea that how I can fixed this?

I guess the moudle which I used to scrapy the cod16 data through https schema. Some certification problem prevent the this.ok() output.

By the way, I can not find how to acquire the **get** params ( like someUrl?a=1&b=2, I want to get param **a** and **b** in the controller action.) from you document  https://thinkkoa.github.io/koatty_doc/#/?id=getname-string

**Comment by richenlin** [comment]
既然能看懂中文文档，我就不用英文沟通了，太累😅

1、获取Get请求的参数可以使用的装饰器有: @Get()、@PathVariable(),  两者功能相同
像这样:

```
.....

@GetMapping("/rechargeList")
    async rechargeList(
        @Get("page") page: number,
        @Get("type") type: number,
        @Get("start_time") start_time: string,
        @Get("end_time") end_time: string
    ) {
   ......
}

......
```

2、你的代码返回了PREVENT_NEXT_PROCESS异常，这是因为在控制器中，this.ok以及 this.fail等方法会通过抛出Promise.reject来中断后续逻辑执行。也就是说，即使方法执行正确，在return this.ok()调用的时候也会抛出PREVENT_NEXT_PROCESS异常来中断后续执行。
如何处理这种问题:
a、推荐使用async/await的写法，而非promise

```
const data = await API.MWwz().catch((err: any) => this.fail(err.message));

return this.ok('success', data);

```
b、如果使用promise的写法，需要先拦截错误，再返回结果。

```
await API.MWwz().catch((err: any) => this.fail(err.message)).then((data: any) => this.ok('', data));
```

另外,我们的文档目前做得不好，我们也正在努力改善

**Comment by yif-fast** [comment]
这是被看穿了嘛？

![1111](https://user-images.githubusercontent.com/56343991/77525717-6841a780-6ec4-11ea-95d6-64380643c4f0.png)

![2222](https://user-images.githubusercontent.com/56343991/77525718-6972d480-6ec4-11ea-8f3b-617e548c3c03.png)

![333](https://user-images.githubusercontent.com/56343991/77525735-6e378880-6ec4-11ea-9cfb-4458583ced86.png)


另外，我看到
![5555](https://user-images.githubusercontent.com/56343991/77525809-90310b00-6ec4-11ea-8c21-06b422bc1b83.png)

状态码是500了。

**Comment by richenlin** [comment]
建议使用调试模式，可以看到详细的错误栈，还可以断点调试，具体方法见文档

启动函数内的这个node_tls的设置可以忽略，它的作用是请求https接口的时候不做签名验证

错误信息已经返回了 你在什么地方使用了‘mode’，但是未定义

至于500错误码，this.fail返回内容的时候，如果不定义错误码。默认是500

**Comment by yif-fast** [comment]
@richenlin 

500解决了。

我代码没几行，

> 这是被看穿了嘛？
> 
> ![1111](https://user-images.githubusercontent.com/56343991/77525717-6841a780-6ec4-11ea-95d6-64380643c4f0.png)

**Comment by yif-fast** [comment]
我去那个https://github.com/Lierrmm/Node-CallOfDuty/issues/10 提问了，我感觉好像也不是他的那个库有问题。

![77519104-e2b8fa00-6eb9-11ea-9954-ae56d1fb41af](https://user-images.githubusercontent.com/56343991/77607277-c5853980-6f54-11ea-8614-4edd0409bb9c.png)

因为数据都已经拿到了，只是在最后一步，reture this.ok的时候，有问题，是不是data的数据格式不对？ 导致它ok失败了？

**Comment by richenlin** [comment]
我前面已经讲到了，控制器输出的数据会自动抛出reject进行中断执行。

所以promise的写法，要把catch放前面。

await API.MWwz('Lierrmm#2364').catch((err: any) => {
    return this.fail(err.message);
}).then((data: any) => {
    return this.ok('', data);
});

**Comment by richenlin** [comment]
而且控制器中输出内容有多个方法
this.ok    输出json格式化的正确结果
this.fail   输出json格式化的错误结果
this.body  输出txt类型的内容
this.json   内容转为json输出
this.jsonp  内容输出为jsonp

**Comment by yif-fast** [comment]
@richenlin 谢谢你耐心的解答，但是我试过，还是不行，我也不知道是哪里出了问题

![000000](https://user-images.githubusercontent.com/56343991/77607872-953e9a80-6f56-11ea-87c1-45b4a6f26ab7.png)

![33333](https://user-images.githubusercontent.com/56343991/77607895-a5ef1080-6f56-11ea-86d4-155864bb78d4.png)


小弟这js水平太低了，搞不定。

**Comment by richenlin** [comment]
把你的CallOfDuty文件发给我，我看看

**Comment by yif-fast** [comment]
@richenlin 太感谢了！叫你大哥啊

![00000](https://user-images.githubusercontent.com/56343991/77608485-50b3fe80-6f58-11ea-9089-fdceed1be60c.png)

**Comment by yif-fast** [comment]
@richenlin 不行，试过了，发不过来！

退信三次了（我换了一个邮箱也不行，退信说是有病毒，我就把整个project打个包）。

![2222](https://user-images.githubusercontent.com/56343991/77609857-16e4f700-6f5c-11ea-80b6-05147d3d56ee.png)


https://github.com/Lierrmm/Node-CallOfDuty
我把 这个库的index.js  放到了node_modules里面，文件夹名为CallOfDuty
我就下载了个index.js文件，然后放到node_modules里面的CallOfDuty文件夹中

使用，就是在indexContorller里面加了个test的action
![33333](https://user-images.githubusercontent.com/56343991/77609996-75aa7080-6f5c-11ea-8152-bbda98b8ea2c.png)


访问就用 http://localhost:3000/test?platform=battle&name=Lierrmm%232364

发邮件发不过来，那个描述就只能这么描述了。

**Comment by yif-fast** [comment]
@richenlin 

![33333333333](https://user-images.githubusercontent.com/56343991/77610984-18fc8500-6f5f-11ea-9626-99be1f9cd2ac.png)

感觉上是这个data本身的问题。

**Comment by richenlin** [comment]
通过调试，我发现，对方的代码第186~189行处理有问题，并且最终返回的数据是一个非数组、非对象的格式，这在js编程里面并不常见。我稍微改了一版，你试试

[demo.zip](https://github.com/thinkkoa/koatty/files/4385119/demo.zip)

**Comment by yif-fast** [comment]
@richenlin 

![11111111](https://user-images.githubusercontent.com/56343991/77612610-8e6a5480-6f63-11ea-9300-5ca30df2464b.png)


搞定了，非常感谢你的耐心的帮助！

**Comment by richenlin** [comment]
star 一下吧😊

**Comment by yif-fast** [comment]
> star 一下吧😊

好的
