### ISSUE TITLE
how to pass params from controller action to view?

### ISSUE THREAD

**Issue by yif-fast** [thinkkoa/koatty#7]
从这个demo里面
https://github.com/thinkkoa/koatty_demo/blob/master/src/controller/Web/WebIndexController.ts
![1111](https://user-images.githubusercontent.com/56343991/77719172-9a1b5100-701f-11ea-95e5-cf47a4fd3bd3.png)

这里有如何安装think_view
![2222](https://user-images.githubusercontent.com/56343991/77719187-a43d4f80-701f-11ea-9010-c117db26e176.png)

但是没有找到如何传参的方法，
点开那个this.render()方法，发现它接收的参数有点奇怪。

![3333](https://user-images.githubusercontent.com/56343991/77719607-a9e76500-7020-11ea-9992-e5f2e457bb9d.png)

又一个文档里面 https://thinkkoa.org/doc/view.jhtml

![4444](https://user-images.githubusercontent.com/56343991/77720121-eebfcb80-7021-11ea-9d54-a627ce44a039.png)

请教下如何使用这个think_view，如何传参。

**Comment by richenlin** [comment]
think_view中间件默认使用了EJS来进行模板渲染。在控制器中，使用assign给模板变量赋值:

```
this.assign("test", "模板变量test");

//渲染模板index.html
this.render("./index.html")
```

然后再模板中用EJS代码获取该变量的值:
```
//index.html

...

<%=test%>
...
```

**Comment by richenlin** [comment]
不过现在的Node.js项目一般都是前后端完全分离的，Node层更多的用于提供API接口，因此传统的MVC方式输出模板用得越来越少了

**Comment by yif-fast** [comment]
@richenlin 



> this.assign("test", "模板变量test");
> 
> //渲染模板index.html
> this.render("./index.html")

只有这种方式么？ shortcut的更简洁的方式？
