### ISSUE TITLE
关于没有配置的页面展示

### ISSUE THREAD

**Issue by heheping** [thinkkoa/koatty#8]
你好，用了你的这个koatty包后能正常使用。配置了首页和一个路由页/search，都能正常使用，目前有个问题。像某些乱写的比如/sea这种没有配置的页面访问后，直接报错暴露了我的后台路径了。想使没配置的页面（除了首页和"/search"）直接访问一个静态404页面 该怎么配置呢？谢谢

**Comment by richenlin** [comment]
框架默认运行在debug模式，该模式下错误页面会显示错误栈，暴露出错误相关文件

您可以运行在生产模式：
直接通过`npm start`启动项目可以运行在生产模式

或者您可以强制设置为生产模式,修改App.ts:

```
...
    public init() {
        // this.root_path = path.dirname(__dirname);
        this.app_debug = true; //线上环境请将debug模式关闭，即：app_debug:false
    }


...
```

**Comment by richenlin** [comment]
至于需要自定义错误页的话，可以修改中间件配置 `middleware.ts`文件:

加入内容:

```
config: { //中间件配置
    Trace: {
            timeout: 30, //http请求超时时间,单位s
            error_code: 500, //报错时的状态码
            error_no_key: "code", //错误号的key
            error_msg_key: "message", //错误消息的key
            error_path: process.env.ROOT_PATH + "/html" //错误模板目录配置.该目录下放置404.html、502.html等,框架会自动根据status进行渲染(支持模板变量,依赖think_view中间件;如果think_view中间件未加载,仅输出模板内容)
        }
}
```

将错误页面放在项目下的html目录内即可

**Comment by heheping** [comment]
> 至于需要自定义错误页的话，可以修改中间件配置 `middleware.ts`文件:
> 
> 加入内容:
> 
> ```
> config: { //中间件配置
>     Trace: {
>             timeout: 30, //http请求超时时间,单位s
>             error_code: 500, //报错时的状态码
>             error_no_key: "code", //错误号的key
>             error_msg_key: "message", //错误消息的key
>             error_path: process.env.ROOT_PATH + "/html" //错误模板目录配置.该目录下放置404.html、502.html等,框架会自动根据status进行渲染(支持模板变量,依赖think_view中间件;如果think_view中间件未加载,仅输出模板内容)
>         }
> }
> ```
> 
> 将错误页面放在项目下的html目录内即可

感谢你的回复，按你说的来可以了 谢谢
